name: notes from seb!
description: stats / R
descriptionLong: A blog about statistics, programming and R.
keywords: R programming statistics

sass:
  sass_dir: assets/css/_sass
  style: :compressed

highlighter: pygments
markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char

url: wahani.github.io #https://wahani.github.io # http://127.0.0.1:4000
permalink: /:year/:month/:title/
owner:
    name: Sebastian Warnholz
    twitter: swarnholz
    github: wahani
    disqus_shortname: wahanigithubio
    linkedin: https://de.linkedin.com/in/sebastianwarnholz

ga_id: UA-48337246-1
ga_username: wahani

timezone: Europe/Berlin

exclude: [_posts/Ideen, *.Rmd, build.R, Makefile, data/*]
