---
layout: post
title: "How to preserve attributes of a data frame"
author: "Sebastian"
categories: [R, fp]
archive: true
---

In the following we have two expressions in which the attributes of a data.frame will be lost.

```{r}
dat <- data.frame(x = 1:10, y = "")
attr(dat, "newAttr") <- 5

# works:
attributes(dat[1:5,])

# dplyr is evil
attributes(dplyr::filter(dat, x %in% 1:5))

```


Can we avoid this by using a S4 data.frame?

```{r, error=TRUE}
library(methods)
S4df <- setClass(
    "S4df",
    contains = "data.frame",
    slots = list("attributes" = "list")
    )

s4dat <- S4df(dat, attributes = attributes(dat))

attributes(dplyr::filter(s4dat, x %in% 1:5)) # does not work...

```


## Okay, functional programming...

```{r}

preserve_attributes <- function(fun) {
    force(fun)
    function(dat) {
        attOfX <- attributes(dat)
        res <- fun(dat)
        attOfRes <- attributes(res)
        attToPreserve <- names(attOfX)[!(names(attOfX) %in% names(attOfRes))]
        attributes(res) <- c(attributes(res), attributes(dat)[attToPreserve])
        res
    }
}

myFilter <- preserve_attributes(
    functional::CurryL(
        dplyr::filter, "..." = x %in% 1:5
        )
    )

attributes(myFilter(dat))

```
